/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-04-16 09:37:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.egovframework.example.bbs;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bbsList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bbsSample/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("jar:file:/D:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bbsSample/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bbsSample/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1419889342000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1586220692805L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.0.9.RELEASE.jar", Long.valueOf(1586417222157L));
    _jspx_dependants.put("jar:file:/D:/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bbsSample/WEB-INF/lib/spring-modules-validation-0.9.jar!/META-INF/spring-commons-validator.tld", Long.valueOf(1204779052000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-modules-validation-0.9.jar", Long.valueOf(1586417027502L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fvalidator_005fjavascript_0026_005fxhtml_005fstaticJavascript_005fformName_005fcdata_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fvalidator_005fjavascript_0026_005fxhtml_005fstaticJavascript_005fformName_005fcdata_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fvalidator_005fjavascript_0026_005fxhtml_005fstaticJavascript_005fformName_005fcdata_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"ko\" xml:lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<title>Sample ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write(' ');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</title>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" />\r\n");
      out.write("\r\n");
      out.write("<!--For Commons Validator Client Side-->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./scripts/lib/jquery-3.5.0.min.js\"></script>\r\n");
      if (_jspx_meth_validator_005fjavascript_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t// 글등록하기\r\n");
      out.write("\tfunction insertBoard(id) {\r\n");
      out.write("\t\tvar title = document.getElementById(\"insertTitle\").value;\r\n");
      out.write("\t\tvar content = document.getElementById(\"insertContent\").value;\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"글등록하려는 아이디값 : \" + id);\r\n");
      out.write("\t\tconsole.log(\"글 등록 제목 : \" + title);\r\n");
      out.write("\t\tconsole.log(\"글 등록 내용 : \" + content);\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"./bbs/saveBoard.do\"\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'id' : '22',\r\n");
      out.write("\t\t\t\t'title' : title,\r\n");
      out.write("\t\t\t\t'content' : content\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(resultData) {\r\n");
      out.write("\t\t\t\tconsole.log(resultData.resultMsg);\r\n");
      out.write("\t\t\t\tmakeList();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 아이디체크&로그인\r\n");
      out.write("\tfunction idCheck() {\r\n");
      out.write("\t\tconsole.log(\">>>idCheck클릭\")\r\n");
      out.write("\r\n");
      out.write("\t\t// 입력된 id\r\n");
      out.write("\t\tvar inputID = document.getElementById(\"inputID\");\r\n");
      out.write("\t\tconsole.log(\"입력한 아이디 : \" + inputID.value);\r\n");
      out.write("\r\n");
      out.write("\t\t// 입력된 password\r\n");
      out.write("\t\tvar inputPass = document.getElementById(\"inputPass\");\r\n");
      out.write("\t\tconsole.log(\"입력한 패스워드 : \" + inputPass.value);\r\n");
      out.write("\r\n");
      out.write("\t\t// 입력된 정보 확인 \r\n");
      out.write("\t\tvar url = \"./bbs/idCheck.do\"\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'id' : inputID.value,\r\n");
      out.write("\t\t\t\t'pass' : inputPass.value\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(resultData) {\r\n");
      out.write("\t\t\t\tconsole.log('로그인한 아이디값 : ' + resultData);\r\n");
      out.write("\t\t\t\tvar tableDorm = document.getElementById('insertBoardTable');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (resultData != null) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 제목\r\n");
      out.write("\t\t\t\t\tvar headTr = document.createElement('tr');\r\n");
      out.write("\t\t\t\t\ttableDorm.appendChild(headTr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd1 = document.createElement('td');\r\n");
      out.write("\t\t\t\t\theadTd1.innerHTML = \"제목\";\r\n");
      out.write("\t\t\t\t\theadTd1.bgColor = \"orange\";\r\n");
      out.write("\t\t\t\t\theadTr.appendChild(headTd1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd2 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd2.setAttribute(\"align\", 'left');\r\n");
      out.write("\t\t\t\t\tvar input = document.createElement('input');\r\n");
      out.write("\t\t\t\t\tinput.setAttribute(\"type\", \"text\");\r\n");
      out.write("\t\t\t\t\tinput.setAttribute(\"name\", \"title\");\r\n");
      out.write("\t\t\t\t\tinput.setAttribute(\"id\", \"insertTitle\");\r\n");
      out.write("\t\t\t\t\theadTd2.appendChild(input);\r\n");
      out.write("\t\t\t\t\theadTr.appendChild(headTd2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 작성자\r\n");
      out.write("\t\t\t\t\tvar headTr2 = document.createElement('tr');\r\n");
      out.write("\t\t\t\t\ttableDorm.appendChild(headTr2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd21 = document.createElement('td');\r\n");
      out.write("\t\t\t\t\theadTd21.innerHTML = \"작성자\";\r\n");
      out.write("\t\t\t\t\theadTd21.bgColor = \"orange\";\r\n");
      out.write("\t\t\t\t\theadTr2.appendChild(headTd21);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd22 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd22.setAttribute(\"align\", 'left');\r\n");
      out.write("\t\t\t\t\theadTd22.innerHTML = resultData;\r\n");
      out.write("\t\t\t\t\theadTr2.appendChild(headTd22);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 내용\r\n");
      out.write("\t\t\t\t\tvar headTr3 = document.createElement('tr');\r\n");
      out.write("\t\t\t\t\ttableDorm.appendChild(headTr3);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd31 = document.createElement('td');\r\n");
      out.write("\t\t\t\t\theadTd31.innerHTML = \"내용\";\r\n");
      out.write("\t\t\t\t\theadTd31.bgColor = \"orange\";\r\n");
      out.write("\t\t\t\t\theadTr3.appendChild(headTd31);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd32 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd32.setAttribute(\"align\", 'left');\r\n");
      out.write("\t\t\t\t\tvar textArea = document.createElement('textarea');\r\n");
      out.write("\t\t\t\t\ttextArea.setAttribute(\"cols\", \"40\");\r\n");
      out.write("\t\t\t\t\ttextArea.setAttribute(\"rows\", \"10\");\r\n");
      out.write("\t\t\t\t\ttextArea.setAttribute(\"name\", \"content\");\r\n");
      out.write("\t\t\t\t\ttextArea.setAttribute(\"id\", \"insertContent\");\r\n");
      out.write("\t\t\t\t\theadTd32.appendChild(textArea);\r\n");
      out.write("\t\t\t\t\theadTr3.appendChild(headTd32);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 글등록\r\n");
      out.write("\t\t\t\t\tvar headTr4 = document.createElement('tr');\r\n");
      out.write("\t\t\t\t\ttableDorm.appendChild(headTr4);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd41 = document.createElement('td');\r\n");
      out.write("\t\t\t\t\theadTd41.setAttribute('colspan', '2');\r\n");
      out.write("\t\t\t\t\theadTd41.setAttribute('align', 'center');\r\n");
      out.write("\t\t\t\t\tvar input2 = document.createElement('input');\r\n");
      out.write("\t\t\t\t\tinput2.setAttribute(\"type\", \"button\");\r\n");
      out.write("\t\t\t\t\tinput2.onclick = function() {\r\n");
      out.write("\t\t\t\t\t\tinsertBoard(resultData);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tinput2.setAttribute(\"id\", \"saveTitle\");\r\n");
      out.write("\t\t\t\t\tinput2.setAttribute(\"value\", \"글등록\");\r\n");
      out.write("\t\t\t\t\theadTd41.appendChild(input2);\r\n");
      out.write("\t\t\t\t\theadTr4.appendChild(headTd41);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"데이터 로딩에 실패했습니다.\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 상세보기\r\n");
      out.write("\tfunction getBoard(bno) {\r\n");
      out.write("\t\tconsole.log(\">>>상세보기\")\r\n");
      out.write("\t\tconsole.log(\"가져온 글번호값 : \" + bno)\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"./bbs/getBoard.do\"\r\n");
      out.write("\t\t$\r\n");
      out.write("\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\turl : url,\r\n");
      out.write("\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t'bno' : bno\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar bno = data.bbsVO.bno;\r\n");
      out.write("\t\t\t\t\t\tvar id = data.bbsVO.id;\r\n");
      out.write("\t\t\t\t\t\tvar title = data.bbsVO.title;\r\n");
      out.write("\t\t\t\t\t\tvar content = data.bbsVO.content;\r\n");
      out.write("\t\t\t\t\t\tvar wdate = data.bbsVO.wdate;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$(\"#listTable\").find(\"tr\").not(\":first\").remove();\r\n");
      out.write("\t\t\t\t\t\t$(\"#listTable\")\r\n");
      out.write("\t\t\t\t\t\t\t\t.append(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<tr><td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ bno\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td><td><input id='inputTitle' type='text' value='\" + title + \"'/></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><input id='inputContent' type='text' value='\" + content + \"'/></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ wdate\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"</td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><input name='modify' type='button' onclick='modifyBoard(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ bno\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \")' value='편집'/></td>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<td><input name='delete' type='button' onclick='deleteBoard(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ bno\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \")' value='삭제'/></td></tr>\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 삭제하기\r\n");
      out.write("\tfunction deleteBoard(bno) {\r\n");
      out.write("\t\tconsole.log(\">>>삭제하기\");\r\n");
      out.write("\t\tconsole.log(\"삭제할 글번호값 : \" + bno);\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"./bbs/deleteBoard.do\"\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'bno' : bno\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tmakeList();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 편집하기\r\n");
      out.write("\tfunction modifyBoard(bno) {\r\n");
      out.write("\t\tconsole.log(\">>>편집하기\");\r\n");
      out.write("\t\tvar title = document.getElementById('inputTitle').value;\r\n");
      out.write("\t\tvar content = document.getElementById('inputContent').value;\r\n");
      out.write("\r\n");
      out.write("\t\tconsole.log(\"편집할 글번호값 : \" + bno);\r\n");
      out.write("\t\tconsole.log(\"편집할 제목값 : \" + title);\r\n");
      out.write("\t\tconsole.log(\"편집할 내용값 : \" + content);\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"./bbs/modifyBoard.do\"\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t'bno' : bno,\r\n");
      out.write("\t\t\t\t'title' : title,\r\n");
      out.write("\t\t\t\t'content' : content\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tmakeList();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 전체보기(Table List 생성)\r\n");
      out.write("\tfunction makeList() {\r\n");
      out.write("\t\tvar tableDom = document.getElementById(\"bbsList\");\r\n");
      out.write("\t\ttableDom.innerHTML = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\tvar url = \"./bbs/bbsList.do\"\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : url,\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar resultList = data.resultList;\r\n");
      out.write("\t\t\t\tif (resultList.length > 0) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTr = document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\t\theadTr.bgColor = \"orange\";\r\n");
      out.write("\t\t\t\t\ttableDom.appendChild(headTr);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd1 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd1.innerHTML = \"글번호\";\r\n");
      out.write("\t\t\t\t\theadTr.appendChild(headTd1);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd2 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd2.innerHTML = \"작성자\";\r\n");
      out.write("\t\t\t\t\theadTr.appendChild(headTd2);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar headTd3 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\theadTd3.innerHTML = \"제목\";\r\n");
      out.write("\t\t\t\t\theadTr.appendChild(headTd3);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tfor (var i = 0; i < resultList.length; i++) {\r\n");
      out.write("\t\t\t\t\t\tvar headTr11 = document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\t\t\ttableDom.appendChild(headTr11);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar headTd11 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\t\theadTd11.innerHTML = resultList[i].bno;\r\n");
      out.write("\t\t\t\t\t\tconsole.log(resultList[i].bno);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\theadTd11.setAttribute('style', 'cursor: pointer');\r\n");
      out.write("\t\t\t\t\t\theadTd11.onclick = function(){\r\n");
      out.write(" \t\t\t\t\t\t\tgetBoard(this.innerHTML);\r\n");
      out.write(" \t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\theadTr11.appendChild(headTd11);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar headTd21 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\t\theadTd21.innerHTML = resultList[i].id;\r\n");
      out.write("\t\t\t\t\t\theadTr11.appendChild(headTd21);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar headTd31 = document.createElement(\"td\");\r\n");
      out.write("\t\t\t\t\t\theadTd31.innerHTML = resultList[i].title;\r\n");
      out.write("\t\t\t\t\t\theadTr11.appendChild(headTd31);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tconsole.log(\"데이터 로딩에 실패했습니다.\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(e) {\r\n");
      out.write("\t\t\t\tconsole.log(e)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 회원가입\r\n");
      out.write("\tfunction userInsert(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"makeList()\">\r\n");
      out.write("\t<!-- 회원가입 -->\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"회원가입\" onclick=\"userInsert()\" /></td>\r\n");
      out.write("\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"id\" id=\"inputID\" /></td>\r\n");
      out.write("\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"pass\" id=\"inputPass\" /></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"button\" value=\"로그인\" onclick=\"idCheck()\" /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t<br />\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 전체 게시글 리스트 -->\r\n");
      out.write("\t<table id=\"bbsList\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" />\r\n");
      out.write("\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<!-- 글등록 -->\r\n");
      out.write("\t<table border=\"1\" id=\"insertBoardTable\" />\r\n");
      out.write("\r\n");
      out.write("\t<br />\r\n");
      out.write("\r\n");
      out.write("\t<!-- 상세보기 -->\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t<table border=\"1\" cellpadding=\"0\" cellspacing=\"0\" id=\"listTable\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">글번호</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">작성자</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">제목</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">내용</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">등록일</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">편집</td>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"orange\">삭제</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("registerFlag");
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(11,0) '${empty sampleVO.id ? 'create' : 'modify'}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${empty sampleVO.id ? 'create' : 'modify'}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(13,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registerFlag == 'create'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_spring_005fmessage_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(14,2) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("button.create");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(15,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${registerFlag == 'modify'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(16,2) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("button.modify");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(20,7) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/css/egovframework/sample.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(23,36) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/cmmn/validator.do");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_validator_005fjavascript_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  validator:javascript
    org.springmodules.validation.commons.taglib.JavascriptValidatorTag _jspx_th_validator_005fjavascript_005f0 = (org.springmodules.validation.commons.taglib.JavascriptValidatorTag) _005fjspx_005ftagPool_005fvalidator_005fjavascript_0026_005fxhtml_005fstaticJavascript_005fformName_005fcdata_005fnobody.get(org.springmodules.validation.commons.taglib.JavascriptValidatorTag.class);
    boolean _jspx_th_validator_005fjavascript_005f0_reused = false;
    try {
      _jspx_th_validator_005fjavascript_005f0.setPageContext(_jspx_page_context);
      _jspx_th_validator_005fjavascript_005f0.setParent(null);
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(25,0) name = formName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_validator_005fjavascript_005f0.setFormName("sampleVO");
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(25,0) name = staticJavascript type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_validator_005fjavascript_005f0.setStaticJavascript("false");
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(25,0) name = xhtml type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_validator_005fjavascript_005f0.setXhtml("true");
      // /WEB-INF/jsp/egovframework/example/bbs/bbsList.jsp(25,0) name = cdata type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_validator_005fjavascript_005f0.setCdata("false");
      int _jspx_eval_validator_005fjavascript_005f0 = _jspx_th_validator_005fjavascript_005f0.doStartTag();
      if (_jspx_th_validator_005fjavascript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fvalidator_005fjavascript_0026_005fxhtml_005fstaticJavascript_005fformName_005fcdata_005fnobody.reuse(_jspx_th_validator_005fjavascript_005f0);
      _jspx_th_validator_005fjavascript_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_validator_005fjavascript_005f0, _jsp_getInstanceManager(), _jspx_th_validator_005fjavascript_005f0_reused);
    }
    return false;
  }
}
